#!/bin/sh
set -e

# This file is run as a cron job and cannot have an extension.
# Viz it must be called pull and not, say, pull.sh
# Pipe it to a file (atomically) for testing.

wget \
  -O- \
  --header='Content-Type:application/json' \
  --post-data='{}' \
  --quiet \
  http://puller:5017/pull \
  | jq . > /tmp/pull.log.tmp

mv /tmp/pull.log.tmp /tmp/pull.log
